ticme_front_categorie:
    resource: "@TicmeFrontBundle/Resources/config/routing/category.yml"
    prefix:   /category

ticme_front_product:
    resource: "@TicmeFrontBundle/Resources/config/routing/product.yml"
    prefix:   /product

ticme_front_homepage:
    path:     /
    defaults: { _controller: TicmeFrontBundle:Default:index }
