ticme_front_categorie:
    resource: "@TicmeFrontBundle/Resources/config/routing/profile.yml"
    prefix:   /profile

ticme_front_categorie:
    resource: "@TicmeFrontBundle/Resources/config/routing/category.yml"
    prefix:   /category

ticme_front_product:
    resource: "@TicmeFrontBundle/Resources/config/routing/product.yml"
    prefix:   /product

ticme_front_cart:
    resource: "@TicmeFrontBundle/Resources/config/routing/cart.yml"
    prefix:   /cart

ticme_front_order:
    resource: "@TicmeFrontBundle/Resources/config/routing/order.yml"
    prefix:   /order

ticme_front_home_page:
    path:     /{page}
    defaults: { _controller: TicmeFrontBundle:Default:index, page: 1 }
    requirements:
      page: \d+

ticme_front_homepage:
    path:     /
    defaults: { _controller: TicmeFrontBundle:Default:index }
