# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    user.form.profile.type:
        class: Ticme\UserBundle\Form\Type\ProfileType
        parent: fos_user.profile.form.type
        tags:
            - { name: form.type, alias: ticme_fos_user_profile }

    user.form.register.type:
        class: Ticme\UserBundle\Form\Type\RegisterType
        parent: fos_user.registration.form.type
        tags:
            - { name: form.type, alias: ticme_fos_user_register }
