ticme_user_user:
    resource: "@TicmeUserBundle/Resources/config/routing/user.yml"
    prefix:   /

ticme_user_client:
    resource: "@TicmeUserBundle/Resources/config/routing/client.yml"
    prefix:   /client