services:
  ticme.services.curUrl:
    class: Ticme\BackBundle\Services\CurlUrl

  ticme.validator.check.url:
    class: Ticme\BackBundle\Validator\Constraints\CheckUrlValidator
    arguments: [@ticme.services.curUrl]
    tags:
      - { name: validator.constraint_validator, alias: validatorCheckUrl }

