ticme_front_address:
    path:     /address
    defaults: { _controller: "TicmeFrontBundle:Address:showCurrentUserAddress" }

ticme_front_invoices:
    path:     /invoices
    defaults: { _controller: "TicmeUserBundle:Invoice:invoices" }

ticme_front_invoicePDF:
    path:     /invoice/pdf/{id}
    defaults: { _controller: "TicmeUserBundle:Invoice:invoicePDF" }